// 统一管理所有 localStorage 键名，避免散落各处导致遗漏
// 修复 S15：重置进度功能清理不完整问题

export const STORAGE_KEYS = {
  PROGRESS: 'color-sort-progress',
  BEST_SCORES: 'color-sort-best-scores',
  TUTORIAL: 'color-sort-tutorial-seen',
  STARS: 'color-sort-stars',
  AUTOSAVE: 'color-sort-autosave',
  RECENT: 'color-sort-recent',
  ENDLESS: 'color-sort-endless',
  TIMED: 'color-sort-timed-highscore',
  ACHIEVEMENTS: 'color-sort-achievements',
  DAILY: 'color-sort-daily',
  SETTINGS: 'color-sort-settings',
  STATS: 'color-sort-stats',
  CHECKIN: 'color-sort-checkin',
  HINT_ITEMS: 'color-sort-hint-items',
  HINT_DAILY_BONUS: 'color-sort-hint-daily-bonus',
  PWA_INSTALL_DISMISSED: 'color-sort-pwa-install-dismissed',
  CHANGELOG_VERSION: 'color-sort-last-version',
  ANNOUNCEMENTS_READ: 'color-sort-announcements-read',
  DAILY_TIP_DATE: 'color-sort-daily-tip-date',
  DAILY_TIP_INDEX: 'color-sort-daily-tip-index',
  DAILY_LEADERBOARD: 'color-sort-daily-leaderboard',
  CUSTOM_LEVELS: 'color-sort-custom-levels',
  VISITS: 'color-sort-visits',
  PLAYED_MODES: 'color-sort-played-modes',
  WEEKEND_BONUS: 'color-sort-weekend-bonus',
  WEEKLY_RECORD: 'color-sort-weekly-record',
  WEEKLY_STREAK: 'color-sort-weekly-streak',
  WEEKLY_HISTORY: 'color-sort-weekly-history',
} as const;

// 导出所有需要重置的键（用于设置页"重置进度"功能）
export const RESETTABLE_KEYS = [
  STORAGE_KEYS.PROGRESS,
  STORAGE_KEYS.BEST_SCORES,
  STORAGE_KEYS.TUTORIAL,
  STORAGE_KEYS.STARS,
  STORAGE_KEYS.AUTOSAVE,
  STORAGE_KEYS.RECENT,
  STORAGE_KEYS.ENDLESS,
  STORAGE_KEYS.TIMED,
  STORAGE_KEYS.ACHIEVEMENTS,
  STORAGE_KEYS.DAILY,
  STORAGE_KEYS.STATS,
  STORAGE_KEYS.CHECKIN,
  STORAGE_KEYS.HINT_ITEMS,
  STORAGE_KEYS.HINT_DAILY_BONUS,
  STORAGE_KEYS.PWA_INSTALL_DISMISSED,
  STORAGE_KEYS.DAILY_LEADERBOARD,
  STORAGE_KEYS.CUSTOM_LEVELS,
  STORAGE_KEYS.VISITS,
  STORAGE_KEYS.PLAYED_MODES,
  STORAGE_KEYS.WEEKEND_BONUS,
  STORAGE_KEYS.WEEKLY_RECORD,
  STORAGE_KEYS.WEEKLY_STREAK,
  STORAGE_KEYS.WEEKLY_HISTORY,
  STORAGE_KEYS.ANNOUNCEMENTS_READ,
  STORAGE_KEYS.DAILY_TIP_DATE,
  STORAGE_KEYS.DAILY_TIP_INDEX,
];

// 导出所有需要备份的键（用于设置页"导出存档"功能）
export const BACKUP_KEYS = [
  STORAGE_KEYS.PROGRESS,
  STORAGE_KEYS.BEST_SCORES,
  STORAGE_KEYS.TUTORIAL,
  STORAGE_KEYS.ACHIEVEMENTS,
  STORAGE_KEYS.DAILY,
  STORAGE_KEYS.TIMED,
  STORAGE_KEYS.STARS,
  STORAGE_KEYS.STATS,
  STORAGE_KEYS.ENDLESS,
  STORAGE_KEYS.SETTINGS,
  STORAGE_KEYS.CHECKIN,
  STORAGE_KEYS.HINT_ITEMS,
  STORAGE_KEYS.HINT_DAILY_BONUS,
  STORAGE_KEYS.RECENT,
  STORAGE_KEYS.AUTOSAVE,
  STORAGE_KEYS.DAILY_LEADERBOARD,
  STORAGE_KEYS.CUSTOM_LEVELS,
  STORAGE_KEYS.VISITS,
  STORAGE_KEYS.PLAYED_MODES,
  STORAGE_KEYS.WEEKEND_BONUS,
  STORAGE_KEYS.WEEKLY_RECORD,
  STORAGE_KEYS.WEEKLY_STREAK,
  STORAGE_KEYS.WEEKLY_HISTORY,
];
